opt_out_usage
default_platform(:ios)

platform :ios do
  desc "create full xcframeworks"
  lane :xcframework do
    swift_protobuf_xcframework
    core_xcframework
  end

  desc "create libprotobuf xcframework"
  lane :protobuf_xcframework do
    create_xcframework(
      workspace: 'TrustWalletCore.xcworkspace',
      scheme: 'protobuf',
      destinations: ['iOS'],
      xcframework_output_directory: 'build',
      enable_bitcode: false,
      product_name: 'libprotobuf'
    )
  end

  # Use this to compile frameworks
  # xcodebuild archive \
  #   -workspace TrustWalletCore.xcworkspace \
  #   -scheme protobuf \
  #   -destination "generic/platform=iOS" \
  #   -archivePath "build/libprotobuf-ios" \
  #   SKIP_INSTALL=NO \
  #   BUILD_LIBRARY_FOR_DISTRIBUTION=YES

  # xcodebuild -create-xcframework \
  #   -library "/Users/mmd/Desktop/everything/Work/GIT/trust-wallet-core/swift/build/libprotobuf-ios.xcarchive/Products/usr/local/lib/libprotobuf.a" \
  #   -library "/Users/mmd/Desktop/everything/Work/GIT/trust-wallet-core/swift/build/libprotobuf-simulator.xcarchive/Products/usr/local/lib/libprotobuf.a" \
  #   -output libprotobuf.xcframework

  desc "create libtrezor-crypto xcframework"
  lane :trezor_xcframework do
    create_xcframework(
      workspace: 'TrustWalletCore.xcworkspace',
      scheme: 'trezor-crypto',
      destinations: ['iOS'],
      xcframework_output_directory: 'build',
      enable_bitcode: false,
      product_name: 'libtrezor-crypto'
    )
  end

  desc "create wallet core xcframework"
  lane :core_xcframework do
    create_xcframework(
      workspace: 'TrustWalletCore.xcworkspace',
      scheme: 'WalletCore',
      destinations: ['iOS'],
      xcframework_output_directory: 'build',
      include_debug_symbols: true,
      enable_bitcode: false
    )
  end

  desc "create swift protobuf xcframework"
  lane :swift_protobuf_xcframework do
    create_xcframework(
      workspace: 'TrustWalletCore.xcworkspace',
      scheme: 'SwiftProtobuf',
      destinations: ['iOS'],
      xcframework_output_directory: 'build',
      include_debug_symbols: true,
      enable_bitcode: false
    )
  end
end
